### ISSUE TITLE
lerna@6.5.0 fails to execute due to `cannot find module 'js-yaml'`

### ISSUE THREAD

**Issue by pachuka** [lerna/lerna#3536]
## Current Behavior

lerna 6.5.0 is missing `js-yaml` as a dependency and fails to run any commands.

This seems to be marked as a `devDependency`, but seems like something has changed between 6.4.1 that now this fails for consumers.

## Expected Behavior

Lerna should not fail on any basic command. Works fine in lerna@6.4.1

## Steps to Reproduce

Yes it's reproducible as is with the sample repo at https://github.com/lerna/repro

### Failure Logs / Configuration

```
 test-lerna % npx lerna -v
Cannot find module 'js-yaml'
Require stack:
- /sources/certainly-lmig/test-lerna/node_modules/lerna/dist/cli.js
```

</p></details>

**Comment by parsoman** [comment]
I am also facing this issue but on lower version of lerna too i.e 3.22.1. Its a blocker for our development activity. Is it widespread impact?

**Comment by buffet-time** [comment]
> I am also facing this issue but on lower version of lerna too i.e 3.22.1. Its a blocker for our development activity. Is it widespread impact?

Can confirm it's causing issues for my company as well that's also not at latest version.

**Comment by pachuka** [comment]
Folks if you are having issues with older versions of Lerna that's not related to this issue, we've been using older versions just fine for many years.

**Comment by buffet-time** [comment]
> Folks if you are having issues with older versions of Lerna that's not related to this issue, we've been using older versions just fine for many years.

so have we until right when this version dropped because of how the `npx` command functions.

**Comment by pachuka** [comment]
For clarity:

1. npx will use latest version if not installed/specified from a `package.json`  aka 6.5.0 - this is the one with the problem
2. if you have a version of `lerna` < 6.5.0 specified in your `package.json` and do install that should still work fine (even with npx, that will use the installed version)
3. having lerna specified in package.json + installed at 6.5.0 will run into this same issue

**Comment by parsoman** [comment]
@pachuka  I think it was caused due to this PR commit https://github.com/lerna/lerna/commit/5eafb62048e97a7d148bf47904c35e652790c1d8#diff-e5695d1a173d077edb3d80c1f8398036778f16ca506c7b803925f2a7f3c21c09L33
where they are making changes in legacy-structure folder.
I dont know if I am right, but everyone is facing this issue.

**Comment by JamesHenry** [comment]
Thanks folks, this is just a simple mistake of missing the `js-yaml` dependency in the lerna package's package.json I will release the fix as `6.5.1` shortly

**Comment by JamesHenry** [comment]
This should hopefully be resolved with `6.5.1` which is now the latest version, thanks all!

**Comment by pachuka** [comment]
Thanks for resolving this so quickly! Confirmed that 6.5.1 resolves the issue.
