### ISSUE TITLE
Error when running `lerna version` after upgrading to 3.17.0

### ISSUE THREAD

**Issue by GeorgeTaveras1231** [lerna/lerna#2295]
## Expected Behavior

Not to get an error

## Current Behavior

```
/Users/gtaveras/code/tkww/tk-platform/union-2/node_modules/@lerna/cli/node_modules/yargs/yargs.js:1148
      else throw err
           ^

TypeError: getUserAgent is not a function
    at Object.<anonymous> (/Users/gtaveras/code/tkww/tk-platform/union-2/node_modules/@lerna/github-client/node_modules/@octokit/endpoint/lib/defaults.js:4:53)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/gtaveras/code/tkww/tk-platform/union-2/node_modules/@lerna/github-client/node_modules/@octokit/endpoint/index.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
## Steps to Reproduce (for bugs)

1. `yarn add lerna@^3.1.7.0`
2. `lerna version`

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.1.2",
  "version": "independent",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "ignoreChanges": [
    "sbm.json",
    "*.test.js",
    "*.test.jsx",
    "*.snap",
    "*.integration-test.js",
    "*.integration-test.jsx",
    "*story.jsx",
    "**/__tests__/**",
    "**/.union-deploy/**",
    "**/__image_snapshots__/**",
    "**/__docs__/**"
  ]
}
```
</p></details>

## Context

I'm just trying to bump package versions

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.17.0 |
| `npm --version`  | 6.4.1 |
| `yarn --version` | 1.17.3 |
| `node --version` | 10.15.3 |

| OS | Version |
| --- | --- |
| macOS High Sierra | 10.13.6 |

**Comment by GeorgeTaveras1231** [comment]
Seems like yarn was incorrectly placing the universal-user-agent dependency in the node_modules. Deleting node_modules and re-installing everything fixed the error 🤷‍♂
