### ISSUE TITLE
LERNA_ROOT_PATH seems not working with node v15.5.0

### ISSUE THREAD

**Issue by RoCat** [lerna/lerna#2787]
Using node v15.5.0 every commands like:
`npx lerna exec --scope my-app -- node \$LERNA_ROOT_PATH/scripts/build.mjs`
are not working. in the logs, it displays:
`Error: Cannot find module '/scripts/build.mjs'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}`

## Expected Behavior
The script should use the correct path.

## Current Behavior
The path seems empty in node 15.5, but is not in node 15.4 ...

## Steps to Reproduce (for bugs)

Just run an exec command with $LERNA_ROOT_PATH in a sample project in node 15.5, it should fail.

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "useWorkspaces": true,
  "npmClient": "yarn",
  "version": "3.6.0-alpha.6"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 verbose cli [
0 verbose cli   '/home/rcatoio/.nvm/versions/node/v15.5.0/bin/node',
0 verbose cli   '/home/rcatoio/.nvm/versions/node/v15.5.0/lib/node_modules/npm/bin/npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--',
0 verbose cli   'lerna',
0 verbose cli   'exec',
0 verbose cli   '--scope',
0 verbose cli   '@doubletrade/desktop',
0 verbose cli   '--',
0 verbose cli   'node',
0 verbose cli   '$LERNA_ROOT_PATH/scripts/rewrite-index.mjs'
0 verbose cli ]
1 info using npm@7.3.0
2 info using node@v15.5.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/home/rcatoio/.nvm/versions/node/v15.5.0/lib/node_modules/npm/npmrc Completed in 0ms
5 timing config:load:builtin Completed in 0ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/home/rcatoio/workspace/insight/monorepo/.npmrc Completed in 1ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/home/rcatoio/.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/home/rcatoio/.nvm/versions/node/v15.5.0/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 7ms
19 verbose npm-session ae8ce83e07110836
20 timing npm:load Completed in 12ms
21 timing command:exec Completed in 429ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/home/rcatoio/.nvm/versions/node/v15.5.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (node:events:376:20)
22 verbose stack     at maybeClose (node:internal/child_process:1063:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:295:5)
23 verbose cwd /home/rcatoio/workspace/insight/monorepo
24 verbose Linux 4.19.128-microsoft-standard
25 verbose argv "/home/rcatoio/.nvm/versions/node/v15.5.0/bin/node" "/home/rcatoio/.nvm/versions/node/v15.5.0/lib/node_modules/npm/bin/npm-cli.js" "exec" "--" "lerna" "exec" "--scope" "@doubletrade/desktop" "--" "node" "$LERNA_ROOT_PATH/scripts/rewrite-index.mjs"
26 verbose node v15.5.0
27 verbose npm  v7.3.0
28 error code 1
29 error path /home/rcatoio/workspace/insight/monorepo
30 error command failed
31 error command sh -c lerna exec --scope @doubletrade/desktop -- node $LERNA_ROOT_PATH/scripts/rewrite-index.mjs
32 verbose exit 1
```
</p></details>

## Context
N/A

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.22.1|
| `npm --version`  | 7.3.0|
| `yarn --version` | 1.22.10|
| `node --version` | v15.5.0|

OS: docker debian buster

**Comment by RoCat** [comment]
It also seems to only happen when using npx, is lerna is globally installed, or directly with ./node_modules/lerna/cli.js the command will work as expected.

**Comment by chriszirkel** [comment]
It's also not working with the node module:

`node ./node_modules/lerna/cli.js exec --scope connector-foundation --stream  -- \"echo 'Root: $LERNA_ROOT_PATH'\"`

gives the following output:

```
> node ./node_modules/lerna/cli.js exec --scope connector-foundation --stream  -- "echo 'Root: $LERNA_ROOT_PATH'"

lerna notice cli v4.0.0
lerna notice filter including "connector-foundation"
lerna info filter [ 'connector-foundation' ]
lerna info Executing command in 1 package: "echo 'Root: '"
connector-foundation: Root: 
lerna success exec Executed command in 1 package: "echo 'Root: '"
```

The LERNA_ROOT_PATH has been replaced by an empty string.

**Comment by fahslaj** [comment]
Closing this issue as it is for a very old version of Lerna.
